### ISSUE TITLE
gitian: "base-trusty-amd64 already exists, please remove it first"

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/docs#16]
`./gitian-build.sh --setup` throws this. Not sure if it's a warning or an error.

**Comment by Sjors** [comment]
It seems safe to ignore.

**Comment by MarcoFalke** [comment]
Let me know if this is still an issue with the most recent version of gitian-build.py

**Comment by justinmoon** [comment]
I just hit this.

The [debian setup instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-the-gitian-image) suggest you run `bin/make-base-vm --lxc --arch amd64 --suite bionic`. Then (later) in the [actual build instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md#initial-gitian-setup) you run `./gitian-build.sh --setup`. [which will execute `make-base-vm` again](https://github.com/bitcoin/bitcoin/blob/2418f739f75824d6689369f326b960cec254cf56/contrib/gitian-build.py#L37), which generates the error/warning. This could cause problems if checks at the end of the function fail to execute.

I think the cleanest way to improve this situation would be to add a `--trusty` flag [gitian-builder.py's `setup()` function](https://github.com/bitcoin/bitcoin/blob/2418f739f75824d6689369f326b960cec254cf56/contrib/gitian-build.py#L11). If this flag is passed we add `--suite trusty` to `make-base-vm` otherwise we add `--suite bionic`.

Then we could delete [this section](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-the-gitian-image) (and fedora analogue)[https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-fedora.md#setting-up-the-gitian-image] and mention in [this section](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md#initial-gitian-setup) that you can pass a `--trusty` flag if you're building pre-0.17.0. And obviously the script would stay backwards-compatible since `bionic` is hard-coded right now and would be the default after this change.

Happy to make a PR if this makes sense.

**Comment by justinmoon** [comment]
I just hit this, but with `base-bionic-amd64 already exists, please remove it first`. I assume you were building pre-0.17.0 before the trusty->bionic switch.

The [debian setup instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-the-gitian-image) suggest you run `bin/make-base-vm --lxc --arch amd64 --suite bionic`. Then (later) in the [actual build instructions](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md#initial-gitian-setup) you run `./gitian-build.sh --setup`. [which will execute `make-base-vm` again](https://github.com/bitcoin/bitcoin/blob/2418f739f75824d6689369f326b960cec254cf56/contrib/gitian-build.py#L37), which generates the error/warning. This could cause problems if checks at the end of the function fail to execute.

I think the cleanest way to improve this situation would be to add a `--suite` flag [gitian-builder.py's `setup()` function](https://github.com/bitcoin/bitcoin/blob/2418f739f75824d6689369f326b960cec254cf56/contrib/gitian-build.py#L11). We could pass this to `make-base-vm`, and default to `bionic`.

Then we could delete [this section](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-the-gitian-image) (and [fedora analogue](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-fedora.md#setting-up-the-gitian-image)) and mention in [this section](https://github.com/bitcoin-core/docs/blob/master/gitian-building.md#initial-gitian-setup) that you can pass a `--suite trusty` flag if you're building pre-0.17.0. And obviously the script would stay backwards-compatible since `bionic` is hard-coded right now and would be the default after this change.

Happy to make a PR if this makes sense.

**Comment by Sjors** [comment]
cc @theuni / @dongcarl / @fanquake

**Comment by MarcoFalke** [comment]
You can only use the manual setup, or the python helper script setup, not both

**Comment by MarcoFalke** [comment]
Gitian has been archived and is no longer actively maintained by us, see #76
